/**
 * Adds the `audit [docsRoot]` row to the command-surface structured-table in
 * docs/20-implementation/10-packages/60-docs-cli. Goes through docs-model's
 * validator + canonical serializer so the bundle stays canonical bytes.
 * (Goldens/CORPUS_PATHS are regenerated by the cascade worker — untouched
 * here.)
 */
import { readFileSync, writeFileSync } from "node:fs";
import {
  serializeDocDocument,
  validateDocDocument,
  type DocDocument,
} from "../packages/docs-model/src/index.ts";

const bundlePath = "docs/20-implementation/10-packages/60-docs-cli/doc.json";
const parsed = JSON.parse(readFileSync(bundlePath, "utf8"));

const before = validateDocDocument(parsed);
if (!before.ok) {
  console.error("existing doc failed validation:", JSON.stringify(before.issues, null, 2));
  process.exit(1);
}
const doc = before.document as DocDocument;

const table = doc.blocks["b-60-docs-cli-command-table-4"];
if (!table || table.type !== "structured-table") {
  console.error("command table block not found");
  process.exit(1);
}
const rows = table.props.rows as string[][];
if (rows.some((row) => row[0]?.startsWith("audit"))) {
  console.log("audit row already present; nothing to do");
  process.exit(0);
}
const linksIndex = rows.findIndex((row) => row[0]?.startsWith("links check"));
if (linksIndex === -1) {
  console.error("links check row not found");
  process.exit(1);
}
rows.splice(linksIndex + 1, 0, [
  "audit [docsRoot]",
  "Machine-checks corpus structural standards. Errors (numbering, missing overviews, invalid doc.json) exit non-zero; warnings are informational.",
]);

const after = validateDocDocument(doc);
if (!after.ok) {
  console.error("edited doc failed validation:", JSON.stringify(after.issues, null, 2));
  process.exit(1);
}
writeFileSync(bundlePath, serializeDocDocument(after.document as DocDocument));
console.log(`wrote ${bundlePath} with audit row`);
