/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types.js"
import type {  MeaningCheck,  MeaningDiff,  RewriteContext,  RewriteFinding,  RewriteResult,  RewriteToken,  SplitCheck } from "./types.js"
import type * as types from "./types.js"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface MeaningCheck {
      differences: MeaningDiff[]
      same?: boolean | null
    }
    export interface MeaningDiff {
      kind?: string | null
      before?: string | null
      after?: string | null
      why?: string | null
    }
    export interface RewriteContext {
      heading?: string | null
      previous?: string | null
      next?: string | null
      parent?: string | null
    }
    export interface RewriteFinding {
      rule_id?: string | null
      message?: string | null
      hint?: string | null
      target?: string | null
    }
    export interface RewriteResult {
      checks?: SplitCheck[] | null
      markdown?: string | null
    }
    export interface RewriteToken {
      token?: string | null
      kind?: "code" | "link" | "reference" | null
      preview?: string | null
    }
    export interface SplitCheck {
      sentence?: string | null
      words?: number | null
      split_at?: string | null
      after_split?: string | null
      after_split_subject?: string | null
      pronouns_after_split: string[]
      w1_under_15_words?: boolean | null
      w2_short_contrast?: boolean | null
      w3_colon_list?: boolean | null
      w4_ends_with_citation?: boolean | null
      w5_scope_opener?: boolean | null
      w6_inside_list_or_before_reason?: boolean | null
      decision?: "keep" | "split" | null
      result?: string | null
    }
}