/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface MeaningCheck {
  differences: MeaningDiff[]
  same: boolean
  
}

export interface MeaningDiff {
  kind: string
  before: string
  after: string
  why: string
  
}

export interface RewriteContext {
  heading?: string | null
  previous?: string | null
  next?: string | null
  parent?: string | null
  
}

export interface RewriteFinding {
  rule_id: string
  message: string
  hint: string
  target: string
  
}

export interface RewriteResult {
  checks?: SplitCheck[] | null
  markdown: string
  
}

export interface RewriteToken {
  token: string
  kind: "code" | "link" | "reference"
  preview: string
  
}

export interface SplitCheck {
  sentence: string
  words: number
  split_at: string
  after_split: string
  after_split_subject: string
  pronouns_after_split: string[]
  w1_under_15_words: boolean
  w2_short_contrast: boolean
  w3_colon_list: boolean
  w4_ends_with_citation: boolean
  w5_scope_opener: boolean
  w6_inside_list_or_before_reason: boolean
  decision: "keep" | "split"
  result: string
  
}
