/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals.js"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    MeaningCheck: ClassViewer<'MeaningCheck', "differences" | "same">;
    
    MeaningDiff: ClassViewer<'MeaningDiff', "kind" | "before" | "after" | "why">;
    
    RewriteContext: ClassViewer<'RewriteContext', "heading" | "previous" | "next" | "parent">;
    
    RewriteFinding: ClassViewer<'RewriteFinding', "rule_id" | "message" | "hint" | "target">;
    
    RewriteResult: ClassViewer<'RewriteResult', "checks" | "markdown">;
    
    RewriteToken: ClassViewer<'RewriteToken', "token" | "kind" | "preview">;
    
    SplitCheck: ClassViewer<'SplitCheck', "sentence" | "words" | "split_at" | "after_split" | "after_split_subject" | "pronouns_after_split" | "w1_under_15_words" | "w2_short_contrast" | "w3_colon_list" | "w4_ends_with_citation" | "w5_scope_opener" | "w6_inside_list_or_before_reason" | "decision" | "result">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "MeaningCheck","MeaningDiff","RewriteContext","RewriteFinding","RewriteResult","RewriteToken","SplitCheck",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.MeaningCheck = this.tb.classViewer("MeaningCheck", [
          "differences","same",
        ]);
        
        this.MeaningDiff = this.tb.classViewer("MeaningDiff", [
          "kind","before","after","why",
        ]);
        
        this.RewriteContext = this.tb.classViewer("RewriteContext", [
          "heading","previous","next","parent",
        ]);
        
        this.RewriteFinding = this.tb.classViewer("RewriteFinding", [
          "rule_id","message","hint","target",
        ]);
        
        this.RewriteResult = this.tb.classViewer("RewriteResult", [
          "checks","markdown",
        ]);
        
        this.RewriteToken = this.tb.classViewer("RewriteToken", [
          "token","kind","preview",
        ]);
        
        this.SplitCheck = this.tb.classViewer("SplitCheck", [
          "sentence","words","split_at","after_split","after_split_subject","pronouns_after_split","w1_under_15_words","w2_short_contrast","w3_colon_list","w4_ends_with_citation","w5_scope_opener","w6_inside_list_or_before_reason","decision","result",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}