import { afterEach, describe, expect, it } from "bun:test";
import { cleanup, render, screen } from "@testing-library/react";
import DocsComponentGallery from "../DocsComponentGallery";

afterEach(() => {
  cleanup();
});

describe("DocsComponentGallery", () => {
  it("renders the registered docs MDX block vocabulary", () => {
    render(<DocsComponentGallery />);

    expect(screen.getByText("Registered Blocks")).toBeTruthy();
    expect(screen.getByText("<Decision>")).toBeTruthy();
    expect(screen.getByText("<Callout>")).toBeTruthy();
    expect(screen.getByText("<AgentContract>")).toBeTruthy();
    expect(screen.getByText("<FileTree>")).toBeTruthy();
    expect(screen.getByText("<Constraint>")).toBeTruthy();
    expect(screen.getByText("<Assumption>")).toBeTruthy();
    expect(screen.getByText("<Risk>")).toBeTruthy();
    expect(screen.getByText("<OpenQuestion>")).toBeTruthy();
    expect(screen.getByText("<Status>")).toBeTruthy();
    expect(screen.getByText("<Milestone>")).toBeTruthy();
    expect(screen.getByText("<Checklist>")).toBeTruthy();
    expect(screen.getByText("<StructuredTable>")).toBeTruthy();
    expect(screen.getByText("<Tabs>")).toBeTruthy();
    expect(screen.getByText("<Columns>")).toBeTruthy();
    expect(screen.getByText("<Code>")).toBeTruthy();
    expect(screen.getByText("<ImplementationMap>")).toBeTruthy();
    expect(screen.getByText("<ApiEndpoint>")).toBeTruthy();
    expect(screen.getByText("<ApiSurface>")).toBeTruthy();
    expect(screen.getByText("<DataModel>")).toBeTruthy();
    expect(screen.getByText("<Diff>")).toBeTruthy();
    expect(screen.getByText("<JsonExplorer>")).toBeTruthy();
    expect(screen.getByText("<AnnotatedCode>")).toBeTruthy();
    expect(screen.getByText("<Diagram>")).toBeTruthy();
    expect(screen.getByText("<Flow>")).toBeTruthy();
    expect(screen.getByText("<Mermaid>")).toBeTruthy();
    expect(screen.getByText("<Wireframe>")).toBeTruthy();
    expect(screen.getByText("<DesignBoard>")).toBeTruthy();
    expect(screen.getByText("<Canvas>")).toBeTruthy();
    expect(screen.getByText("<Artboard>")).toBeTruthy();
    expect(screen.getByText("<Screen>")).toBeTruthy();
    expect(screen.getByText("<Prototype>")).toBeTruthy();
    expect(screen.getByText("<PrototypeScreen>")).toBeTruthy();
    expect(screen.getByText("<PrototypeTransition>")).toBeTruthy();
    expect(screen.getAllByText("replace-mdx-block").length).toBeGreaterThan(0);
    expect(screen.getByText("append-file-tree-entry")).toBeTruthy();
    expect(screen.getByText("append-checklist-item")).toBeTruthy();
    expect(screen.getByText("append-tab")).toBeTruthy();
    expect(screen.getByText("update-code-body")).toBeTruthy();
    expect(screen.getByText("append-implementation-entry")).toBeTruthy();
    expect(screen.getByText("update-api-endpoint-param")).toBeTruthy();
    expect(screen.getByText("append-api-surface-endpoint")).toBeTruthy();
    expect(screen.getByText("append-data-entity")).toBeTruthy();
    expect(screen.getByText("update-diff-after")).toBeTruthy();
    expect(screen.getByText("update-json-explorer-json")).toBeTruthy();
    expect(screen.getByText("append-code-annotation")).toBeTruthy();
    expect(screen.getByText("append-diagram-node")).toBeTruthy();
    expect(screen.getByText("append-diagram-edge")).toBeTruthy();
    expect(screen.getByText("append-flow-step")).toBeTruthy();
    expect(screen.getByText("update-mermaid-source")).toBeTruthy();
    expect(screen.getByText("append-wireframe-region")).toBeTruthy();
    expect(screen.getAllByText("append-artboard").length).toBeGreaterThan(0);
    expect(screen.getAllByText("append-board-connector").length).toBeGreaterThan(0);
    expect(screen.getByText("append-screen-region")).toBeTruthy();
    expect(screen.getByText("append-prototype-screen")).toBeTruthy();
    expect(screen.getByText("append-prototype-transition")).toBeTruthy();
    expect(screen.getByText("update-prototype-transition")).toBeTruthy();
  });
});
