import type { AccentFamily, FontChoice, NumberFontChoice, CodeFontChoice, CodePanelMode, PageAlignment, PeekDividerStyle, ReferenceIconPosition, GrainBlendMode } from "../../../../shared/style-rail-settings";

const ACCENT_OPTIONS: Array<{ id: AccentFamily; label: string }> = [
  { id: "blue", label: "Blue" },
  { id: "purple", label: "Purple" },
  { id: "pink", label: "Pink" },
  { id: "red", label: "Red" },
  { id: "orange", label: "Orange" },
  { id: "yellow", label: "Yellow" },
  { id: "green", label: "Green" },
  { id: "brown", label: "Brown" },
  { id: "gray", label: "Gray" },
];

const FONT_OPTIONS: Array<{ id: FontChoice; label: string }> = [
  { id: "sans", label: "Inter" },
  { id: "serif", label: "Serif" },
  { id: "mono", label: "Mono" },
];

const NUMBER_FONT_OPTIONS: Array<{ id: NumberFontChoice; label: string }> = [
  { id: "body", label: "Body font" },
  ...FONT_OPTIONS,
];

const CODE_FONT_OPTIONS: Array<{ id: CodeFontChoice; label: string }> = [
  ...FONT_OPTIONS,
  { id: "plex-mono", label: "IBM Plex Mono" },
];

const CODE_PANEL_OPTIONS: Array<{ id: CodePanelMode; label: string }> = [
  { id: "dark", label: "Always dark" },
  { id: "page", label: "Follow page" },
];

const PAGE_ALIGNMENT_OPTIONS: Array<{ id: PageAlignment; label: string }> = [
  { id: "left", label: "Left" },
  { id: "centered", label: "Centered" },
];

const PEEK_DIVIDER_STYLE_OPTIONS: Array<{ id: PeekDividerStyle; label: string }> = [
  { id: "solid", label: "Solid" },
  { id: "dashed", label: "Dashed" },
  { id: "dotted", label: "Dotted" },
  { id: "double", label: "Double" },
];

const REFERENCE_ICON_POSITION_OPTIONS: Array<{
  id: ReferenceIconPosition;
  label: string;
}> = [
  { id: "before", label: "Before text" },
  { id: "after", label: "After text" },
];

const BLEND_OPTIONS: Array<{ id: GrainBlendMode; label: string }> = [
  { id: "auto", label: "Auto" },
  { id: "multiply", label: "Multiply · darken" },
  { id: "screen", label: "Screen · lighten" },
  { id: "overlay", label: "Overlay" },
  { id: "normal", label: "Normal" },
];

const TOKEN_KEY_LABELS: Record<string, string> = {
  fg: "Text",
  bg: "Background",
  border: "Border",
  infoAccent: "Info accent",
  infoTint: "Info tint",
  infoTitleFg: "Info title text",
  decisionAccent: "Decision accent",
  decisionTint: "Decision tint",
  decisionTitleFg: "Decision title text",
  warningAccent: "Warning accent",
  warningTint: "Warning tint",
  warningTitleFg: "Warning title text",
  riskAccent: "Risk accent",
  riskTint: "Risk tint",
  riskTitleFg: "Risk title text",
  pathFg: "Path text",
  stringFg: "String text",
  typeFg: "Type name text",
  callFg: "Call text",
  literalFg: "Number text",
  keywordLiteralFg: "Keyword text",
  propFg: "Key text",
  successAccent: "Success accent",
  successTint: "Success tint",
  successTitleFg: "Success title text",
  marker: "Marker",
  itemGap: "Item gap",
  caption: "Caption",
  captionTextSize: "Caption text size",
  captionGap: "Caption gap",
  note: "Note",
  borderWidth: "Border width",
  hairlineWidth: "Hairline width",
  padY: "Padding Y",
  padX: "Padding X",
  margin: "Margin",
  marginTop: "Space above",
  marginBottom: "Space below",
  spacing: "Spacing (em)",
  thickness: "Thickness",
  folderFg: "Folder names",
  folderWeight: "Folder weight",
  fileFg: "File names",
  fileWeight: "File weight",
  guide: "Tree lines",
  mutedFg: "Muted text",
  added: "Added",
  removed: "Removed",
  modified: "Modified",
  renamed: "Renamed",
  changeTint: "Change tint strength",
  headerBg: "Header background",
  headerFg: "Header text",
  headerRule: "Header rule",
  headerRuleWidth: "Header rule width",
  headerRuleOpacity: "Header rule opacity",
  rowRule: "Row rule",
  rowRuleWidth: "Row rule width",
  rowRuleOpacity: "Row rule opacity",
  columnRule: "Column rule",
  columnRuleWidth: "Column rule width",
  columnRuleOpacity: "Column rule opacity",
  rowHoverBg: "Row hover background",
  name: "Names",
  type: "Types",
  rule: "Rules",
  sigName: "Signature name",
  sigType: "Signature type",
  sigPunct: "Signature punctuation",
  noteName: "Note name",
  noteType: "Note type",
  noteFg: "Note text",
  descFg: "Description text",
  childRule: "Child rule",
  rowPad: "Row padding",
  rowMinHeight: "Row min height",
  optionalFg: "Optional marker",
  nameWeight: "Name weight",
  typeTextSize: "Type text size",
  headerTextSize: "Header text size",
  headerWeight: "Header weight",
  headerPadY: "Header padding Y",
  columnHeadTextSize: "Column head text size",
  columnHeadPadY: "Column head padding Y",
  paneRuleWidth: "Pane divider width",
  childRuleWidth: "Child rule width",
  descTextSize: "Description text size",
  nameWidth: "Name column width",
  descLineHeight: "Description line height",
  columnHeadFg: "Column head text",
  noteNameTextSize: "Note name size",
  noteNameWeight: "Note name weight",
  noteTypeTextSize: "Note type size",
  cellPaddingY: "Row padding",
  cellPaddingX: "Cell padding",
  fontSize: "Text size",
  bodyWeight: "Body weight",
  titleFg: "Title text",
  keyFg: "Key column text",
  titleTextSize: "Title text size",
  titleWeight: "Title weight",
  radius: "Corner radius",
  handleRadius: "Handle radius",
  handleOffset: "Handle offset",
  selectionPadding: "Selection padding",
  color: "Color",
  string: "Strings",
  number: "Numbers",
  boolean: "Booleans",
  null: "Null",
  key: "Keys",
  punctuation: "Plain text",
  keyword: "Keywords",
  control: "Control keywords",
  function: "Functions",
  comment: "Comments",
  regex: "Regex",
  tag: "Tags",
  constant: "Constants",
  selector: "Selectors",
  muted: "Muted fill",
  icon: "Icons",
  languageFg: "Language picker hover",
  annotationAccent: "Annotation accent",
  gutterFg: "Line numbers",
  gutterBg: "Gutter background",
  headerHeight: "Header height",
  gutterTextSize: "Line number size",
  gutterWidth: "Gutter width",
  gutterPadX: "Gutter padding",
  padTop: "Top padding",
  padBottom: "Bottom padding",
  notesWidth: "Notes column width",
  weight: "Weight",
  zebra: "Zebra stripe",
  highlight: "Link highlight",
  pin: "Pin & rail",
  washStrength: "Highlight strength",
  railWidth: "Rail width",
  ringWidth: "Pin ring width",
  ink: "Ink",
  deepInk: "Deep ink",
  rail: "Rail",
  cycle1: "Depth 1 color",
  cycle2: "Depth 2 color",
  cycle3: "Depth 3 color",
  cycle4: "Depth 4 color",
  cycle5: "Depth 5 color",
  cycle6: "Depth 6 color",
  keywordFg: "Loop keyword",
  keywordWeight: "Loop keyword weight",
  noteBg: "Note background",
  noteBorder: "Note border",
  noteRule: "Note rule",
  noteBullet: "Note bullets",
  codeBg: "Code background",
  indent: "Indent",
  rowGap: "Row gap",
  branchGap: "Branch gap",
  rootGap: "Root gap",
  arrowGap: "Elbow gap",
  lineHeight: "Line height",
  textSize: "Text size",
  bodyTextScale: "Body text scale",
  h1Size: "H1 size (em)",
  h2Size: "H2 size (em)",
  h3Size: "H3 size (em)",
  iconSize: "Icon size",
  rootTextSize: "Root text size",
  rootWeight: "Root weight",
  branchWeight: "Sublayer 1 weight",
  stepWeight: "Sublayer weight",
  emptyTextSize: "Empty text size",
  noteTextSize: "Note text size",
  noteLineHeight: "Note line height",
  noteInset: "Note inset",
  noteBorderWidth: "Note border width",
  noteRuleWidth: "Note rule width",
  notePadY: "Note padding Y",
  notePadX: "Note padding X",
  noteRuleGap: "Note rule gap",
  noteAccent: "Note accent strength",
  traceTextSize: "Trace pill size",
  focusRing: "Focused line ring",
  selectBg: "Selected line background",
  selectTint: "Selected line tint",
  selectPad: "Selected line padding",
  stroke: "Stroke",
  padding: "Padding",
  maxHeight: "Max preview height",
  expandFg: "Expand label",
  expandTextSize: "Expand label size",
  diagramBg: "Diagram background",
  diagramText: "Diagram text",
  diagramLine: "Diagram lines",
  actorFill: "Actor fill",
  actorBorder: "Actor border",
  fragment: "Fragment frame",
  ruleWidth: "Rule width",
  ruleOpacity: "Rule opacity",
  zebraOpacity: "Zebra opacity",
  notesBg: "Notes background",
  selection: "Selection",
  actionFg: "Action badge text",
  actionLine: "Action badge border",
  actionSoft: "Action badge fill",
  queryFg: "Query badge text",
  queryLine: "Query badge border",
  querySoft: "Query badge fill",
  eventFg: "Event badge text",
  eventLine: "Event badge border",
  eventSoft: "Event badge fill",
  commentFg: "Comment text",
  commentTextSize: "Comment text size",
  sourceTextSize: "Source text size",
  addedBg: "Added background",
  removedBg: "Removed background",
  modifiedBg: "Modified background",
  variable: "Variables",
  punct: "Punctuation",
  bracket: "Tag brackets",
  detailFg: "Detail text",
  cardBg: "Card background",
  arrow: "Arrows",
  boundary: "Boundary lines",
  gap: "Gap",
  blue: "Blue layer",
  green: "Green layer",
  yellow: "Yellow layer",
  orange: "Orange layer",
  purple: "Purple layer",
  red: "Red layer",
  pink: "Pink layer",
  gray: "Gray layer",
};

export { ACCENT_OPTIONS, FONT_OPTIONS, NUMBER_FONT_OPTIONS, CODE_FONT_OPTIONS, CODE_PANEL_OPTIONS, PAGE_ALIGNMENT_OPTIONS, PEEK_DIVIDER_STYLE_OPTIONS, REFERENCE_ICON_POSITION_OPTIONS, BLEND_OPTIONS, TOKEN_KEY_LABELS };
