import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {resolve,join} from 'node:path';
import {writeFile,access} from 'node:fs/promises';
const repo=resolve(import.meta.dir,'../../..');const client=new Client({name:'maintenance-export',version:'1'});
const paths=['40-guides','40-guides/10-docs-mcp',...['10-setup','20-skills','30-sync','40-recovery','50-document-management'].map(x=>'40-guides/10-docs-mcp/'+x),'30-implementation/10-packages/85-docs-mcp'];
const esc=(s:any)=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const id=(s:string)=>s.replaceAll('/','--');const docs:any[]=[];let refs=0;
try{await client.connect(new StdioClientTransport({command:process.execPath,args:[join(repo,'packages/docs-mcp/src/cli.ts'),'mcp','--workspace',resolve(repo,'..')]}));
async function call(name:string,args:any){const r=await client.callTool({name,arguments:args});if(r.isError)throw Error(JSON.stringify(r.structuredContent));return r.structuredContent as any;}
const found=await call('docs_discover',{});const project=found.projects.find((p:any)=>p.name==='docs-system').id;
for(const path of paths){const r=await call('docs_read',{project,path});docs.push({path,...r});for(const b of Object.values(r.doc.blocks) as any[]){for(const s of b.text??[]){const ref=s.attributes?.reference;if(ref?.kind==='doc'){await call('docs_read',{project,path:ref.path});refs++;}if(ref?.kind==='source'){await access(join(repo,ref.path));refs++;}}}}
const spans=(ss:any[])=>ss.map(s=>{const ref=s.attributes?.reference;return ref?.kind==='doc'&&paths.includes(ref.path)?`<a href="#${id(ref.path)}">${esc(s.insert)}</a>`:esc(s.insert)}).join('');
function block(b:any):string{const text=spans(b.text??[]);if(b.type==='heading')return `<h3>${text}</h3>`;if(b.type==='code')return `<pre><code>${text}</code></pre>`;if(b.type==='structured-table')return `<div class="table"><table><thead><tr>${b.props.columns.map((c:any)=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${b.props.rows.map((r:any)=>`<tr>${r.map((c:any)=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;if(b.type==='file-tree')return `<div class="table"><table>${b.props.entries.map((e:any)=>`<tr><td><code>${esc(e.path)}</code></td><td>${esc(e.note)}</td></tr>`).join('')}</table></div>`;return text?`<p>${text}</p>`:'';}
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Codecaine Docs MCP Maintenance</title><style>body{margin:0;background:#f5f6f3;color:#172b2a;font:17px/1.65 system-ui}main{max-width:1050px;margin:auto;padding:40px 24px}section{background:white;border:1px solid #dce4dc;border-radius:12px;padding:28px;margin:24px 0}h1,h2,h3{line-height:1.25}h3{margin-top:32px}a{color:#096c67}pre{background:#14282e;color:#e4eee9;padding:18px;border-radius:8px;white-space:pre-wrap;overflow-wrap:anywhere}code{font-size:13px}td,th{padding:12px;text-align:left;vertical-align:top;border-bottom:1px solid #dce4dc}table{border-collapse:collapse;width:100%;font-size:14px}.table{overflow:auto}nav a{display:block;padding:4px}p{max-width:85ch}</style><main><h1>Docs MCP Maintenance</h1><p>Generated from the maintained Docs corpus on September 14, 2026. Edit the canonical pages through Docs tools, then regenerate this reading copy. This file does not configure or deploy anything.</p><nav>${docs.slice(1).map(d=>`<a href="#${id(d.path)}">${esc(d.doc.title)}</a>`).join('')}</nav>${docs.slice(1).map(d=>`<section id="${id(d.path)}"><h2>${esc(d.doc.title)}</h2>${d.doc.blocks[d.doc.root].children.map((bid:string)=>block(d.doc.blocks[bid])).join('')}</section>`).join('')}</main></html>`;
await writeFile(join(repo,'objectives/docs-mcp-integration/maintenance-reference.html'),html);
await writeFile(join(import.meta.dir,'maintenance-reference-checks.json'),JSON.stringify({pages:docs.map(d=>({path:d.path,hash:d.hash})),validatedReferences:refs},null,2)+'\n');console.log(`Exported ${docs.length} pages; validated ${refs} references.`);
}finally{await client.close();}
