import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import {resolve,join} from 'node:path';
import {readFile,writeFile,access} from 'node:fs/promises';
const repo=resolve(import.meta.dir,'../../..'), core=resolve(repo,'..');
const client=new Client({name:'docs-maintenance-author',version:'1.0'});
const evidence:any[]=[];
async function call(name:string,args:any={}){const r=await client.callTool({name,arguments:args});const d:any=r.structuredContent;evidence.push({name,path:args.path,ok:!r.isError,...(name==='docs_check'?{result:d}:{})});if(r.isError)throw Error(JSON.stringify(d));return d;}
const p=(s:string)=>({type:'paragraph',text:[{insert:s}],props:{}});
const h=(s:string)=>({type:'heading',text:[{insert:s}],props:{level:2}});
const c=(s:string,language='sh')=>({type:'code',text:[{insert:s}],props:{language}});
const link=(label:string,path:string,tail:string,kind='doc')=>({type:'paragraph',props:{},text:[{insert:label,attributes:{reference:{kind,path}}},{insert:tail}]});
const table=(columns:string[],rows:string[][])=>({type:'structured-table',props:{columns,rows}});
const tree=(rows:string[][])=>({type:'file-tree',props:{entries:rows.map(([path,note])=>({path,note}))}});
const base='30-guides/10-docs-mcp', impl='20-implementation/10-packages/85-docs-mcp';
const specs:any[]=[
{path:'30-guides',title:'Guides',blocks:[p('This guides tier contains non-normative operating and maintenance procedures. The foundation, system design, and implementation documents own the contracts. These guides explain how to use and maintain those contracts; they do not introduce project-specific standards.'),link('Docs MCP Maintenance',base,' explains installation, multi-project discovery, skills, updates, and recovery.')]},
{path:base,title:'Docs MCP Maintenance',blocks:[p('Start with the procedure that matches the change. These guides cover the local development checkout and its external coding-agent connections.'),link('Docs MCP',impl,' owns the architecture, source ownership, and runtime boundaries.'),link('Client Setup and Project Discovery',base+'/10-setup',' connects Codex, Claude Code, and pi to documentation corpora.'),link('Skills and Component Knowledge',base+'/20-skills',' identifies the maintained sources and explains how to change them.'),link('Synchronization and Updates',base+'/30-sync',' maps each change to regeneration, installation, restart, and verification.'),link('Validation and Recovery',base+'/40-recovery',' provides repeatable acceptance checks and failure recovery.')]},
{path:base+'/10-setup',title:'Client Setup and Project Discovery',blocks:[
p('Run commands from the docs-system repository unless a step names another directory. This installation references the development checkout through absolute paths. Keep Bun and the checkout available to each client.'),
h('Install the Connection'),
p('1. Install workspace dependencies from the parent Core directory. Its workspace lockfile owns the linked package dependencies.'),c('cd ..\nbun install\ncd docs-system'),
p('2. Preview the installation. Use --clients codex,claude,pi to select clients, or omit the flag for all three. Preview does not change client files.'),c('bun packages/docs-mcp/src/cli.ts install'),
p('3. Write the installation and save its report. Changed files receive backups. The saved report is the input to the guarded restore command.'),c('bun packages/docs-mcp/src/cli.ts install --write > /tmp/codecaine-docs-install.json\nbun packages/docs-mcp/src/cli.ts doctor'),
p('4. Restart Codex and Claude Code. In pi, run /reload. Open a new task in the target workspace so the client can load the installed skill and tools.'),
h('Client Files'),table(['Client','Connection','Skill location'],[
['Codex','MCP stdio entry mcp_servers.codecaine-docs in ~/.codex/config.toml; CODEX_HOME changes the config directory.','~/.agents/skills/codecaine-docs'],
['Claude Code','MCP stdio entry mcpServers.codecaine-docs in ~/.claude.json.','~/.claude/skills/codecaine-docs'],
['pi Agent','~/.pi/agent/extensions/codecaine-docs.ts imports the bridge from the checkout; PI_CODING_AGENT_DIR changes the pi directory.','~/.agents/skills/codecaine-docs']]),
p('The installer preserves unrelated settings and refuses an unmanaged entry with the same name. Its --home option supports alternate home directories. Custom Claude paths require installer API options; the CLI does not expose every custom path setting. Inspect the preview before writing a customized installation.'),
h('Discover the Workspace'),
p('A single connection routes operations to explicit project IDs. Start in a project to work on its docs, or in Core to discover multiple declared projects. Discovery uses the workspace itself, members.json directory entries, supported package workspace patterns, and explicit projects in codecaine.docs.json. It does not scan the whole machine.'),c('bun packages/docs-mcp/src/cli.ts discover --workspace ..'),
p('The workspace defaults to --workspace, then CLAUDE_PROJECT_DIR, then the process working directory. MCP roots can update the client workspace. pi passes its session directory. If discovery is wrong, explicitly supply the intended absolute workspace to docs_discover and begin a new task there.'),
p('Use this optional configuration in a project or umbrella workspace. Omit projects for a single repository. The docsRoot directory must contain at least one valid normalized doc.json bundle.'),c('{\n  "name": "my-workspace",\n  "docsRoot": "docs",\n  "products": ["docs"],\n  "projects": ["child-project-a", "child-project-b"]\n}','json'),
p('Member paths must remain inside the workspace. docsRoot must remain inside its project, including after resolving symlinks. Absolute member paths and recursive ** globs are unsupported. Declare explicit relative members instead. Markdown-only repositories are not migrated; malformed candidate bundles produce discovery warnings.'),
p('Project IDs depend on the project name and canonical docs-root path. Rediscover after moving or renaming a checkout. For a prompt that edits two projects, use the two returned IDs on separate tool calls and check each changed page. There is no cross-project transaction or rollback.'),
h('Inspect Changes in the Shared UI'),c('bun packages/docs-mcp/src/cli.ts ui --workspace .. --project docs-system --port 4808'),
p('This workbench uses the same editing service as the external clients. Valid tool edits become visible immediately. Existing standalone or kernel workbenches have separate process-local coordination; finish their edits before editing the same documents through MCP.'),
p('Website publication remains a separate build, export, or embedding integration over the corpus. Editing a document does not deploy it. The local MCP service is not the public website server.') ]},
{path:base+'/20-skills',title:'Skills and Component Knowledge',blocks:[
p('Change the maintained source, regenerate derived references, and refresh installed copies. Editing an installed skill alone creates a local difference that the next installation can overwrite.'),
link('Docs MCP',impl,' describes the service and the shared authoring context.'),
h('Maintained Sources'),
link('packages/docs-mcp/skills/codecaine-docs/SKILL.md','packages/docs-mcp/skills/codecaine-docs/SKILL.md',' owns the external-agent workflow, trigger description, and skill metadata.','source'),
link('packages/docs-model/src/authoring-guidance.ts','packages/docs-model/src/authoring-guidance.ts',' owns AUTHORING_BUNDLES, the standard and style document lists, component catalog assembly, and shared rendering.','source'),
link('packages/docs-model/src/components/index.ts','packages/docs-model/src/components/index.ts',' registers component bundles. Each component manifest supplies authoring metadata with whenToUse, example, and docsPath.','source'),
link('packages/docs-model/src/visual-component-guidance.ts','packages/docs-model/src/visual-component-guidance.ts',' owns the shared visual-selection text used with the component catalog.','source'),
link('packages/docs-mcp/src/guidance.ts','packages/docs-mcp/src/guidance.ts',' loads and validates canonical documents, hashes guidance sources, and generates portable skill references.','source'),
h('What the Agent Receives'),
p('The server advertises tools and startup instructions. docs_begin returns the writing standards, full component-selection catalog, task ID, and snapshot identity. docs_guidance can retrieve one component reference by component name. The MCP resource codecaine://docs/guidance exposes current rendered guidance. There is no MCP prompts capability in this implementation.'),
p('The installed skill tells the coding agent when and how to use those tools. Installation places references/standards.md, references/components.md, references/components/<name>.md, and snapshot.json beside SKILL.md. These files are generated from the canonical corpus and manifests; they are not independent standards.'),
p('The catalog covers rich text, annotated Code, File Tree, Structured Table, State Shape, Interaction Surface, Canvas, Sequence, and Process Outline. Component purposes load together; detailed references can be fetched only when needed. Connecting an MCP does not prove a client selected the skill. Test implicit use in each client.'),
h('Change Writing or Component Guidance'),
p('1. For wording and standards, read the canonical document through Docs tools, apply a typed edit, and run docs_check. For tool-use workflow, edit the source SKILL.md. Project-specific standards overrides are not implemented.'),
p('2. For component selection, update the component manifest authoring metadata and its canonical reference together. Change the shared visual guidance only when the selection rule itself changes.'),
p('3. For a new component, register its bundle, state schema, typed actions, and rendering using the existing component contract. Add its canonical documentation and manifest metadata. A skill reference alone does not implement editing tools.'),
p('4. Refresh the client installation and begin a new authoring task. Restart the service first when imported TypeScript changed. Inspect docs_guidance for the changed component and verify a real typed edit.'),
link('Synchronization and Updates',base+'/30-sync',' gives the commands and restart decisions.'),
h('Built-in Agents and PromptKit'),
p('The Docs Lab context loader at packages/docs-kernel/catalog/docs-lab-editor/context/index.ts and the sibling agent-kernel/catalog/docs-writer/context/index.ts both use the shared authoring-guidance renderer. Their prompts, model configuration, context loading, and staged editing sessions remain owned by those agents. External MCP edits do not run those agents.'),
p('PromptKit remains responsible for its own prompt machinery. This integration has no PromptKit editing adapter and does not turn every internal prompt into an MCP prompt. A future product service can follow the same separation between typed operations, maintained knowledge, and client installation. Such adapters must document their own state ownership and validation before claiming coverage.') ]},
{path:base+'/30-sync',title:'Synchronization and Updates',blocks:[
p('Use this runbook when code, standards, skill instructions, or checkout locations change. Synchronization currently means shared source rendering, generated installed references, and explicit process reloads. It is not an automatic package-release resolver.'),
link('Docs MCP',impl,' defines the runtime boundaries this runbook operates within.'),
h('Choose the Refresh'),table(['Changed item','Refresh required','Verify'],[
['Canonical standard, style, or component document','New docs_begin loads current corpus text. Reinstall to refresh installed references. Existing tasks retain their snapshot.','Inspect docs_guidance and the new snapshot ID.'],
['Source SKILL.md','Reinstall and start a fresh client task so the new skill is loaded.','Doctor and an implicit documentation request.'],
['Manifest, renderer, tool schema, store, or imported runtime code','Finish tasks; stop service; reconnect clients; restart shared UI; regenerate/install when guidance changed.','New docs_begin, tools listing, affected tests, and a real edit.'],
['Checkout location or Bun path','Reinstall absolute client paths; stop the old checkout service before switching. Rediscover projects.','Doctor, discovery, and docs_begin.'],
['Package dependency or version','Install dependencies at Core root; restart affected processes; record a new snapshot.','Typecheck and affected package/internal-session tests.']]),
h('Generate and Install'),c('bun packages/docs-mcp/src/cli.ts guidance --write\nbun packages/docs-mcp/src/cli.ts install\nbun packages/docs-mcp/src/cli.ts install --write > /tmp/codecaine-docs-refresh.json\nbun packages/docs-mcp/src/cli.ts doctor'),
p('guidance --write refreshes references in the package skill directory. The installer also generates current references in a temporary directory while building its planned changes, so installation does not depend on manually generated copies being current. Keep the source and installed locations distinct. Review generated reference changes instead of editing them by hand.'),
h('Reload Runtime Code'),
p('1. End active documentation tasks after checking their changed pages. Finish any standalone or kernel editing activity on the same documents.'),c('bun packages/docs-mcp/src/cli.ts status\nbun packages/docs-mcp/src/cli.ts stop\nbun packages/docs-mcp/src/cli.ts start'),
p('2. Reconnect coding clients and restart shared workbenches. Workbenches bind to the service URL and token at launch. Begin a new task and read fresh hashes before continuing.'),
p('3. Run the affected validation checks and record a snapshot after the code and guidance settle.'),c('bun test packages/docs-mcp/src\nbunx tsc -p packages/docs-mcp/tsconfig.json --noEmit\nbun packages/docs-mcp/src/cli.ts snapshot --out /tmp/codecaine-docs-snapshot.json'),
h('What a Snapshot Records'),
p('The development manifest records runtime package source hashes, repository commits and dirty flags, guidance sources and identity, client declarations, and the tool-contract hash. Source hashing covers package.json and selected src TypeScript and JSON files, excluding tests and fixtures. A snapshot identifies these inputs; it is not a full repository archive.'),
p('Runtime coverage includes docs-mcp, docs-model, docs-server, docs-index, docs-workbench, Canvas, Sequence, and Annotations. Repository metadata includes docs-system, canvas, sequence, annotations, agent-kernel, and prompt-kit. A recorded repository is not proof that it has a product adapter or normalized documentation corpus.'),
p('The package is currently private and uses workspace dependencies. The skill has version metadata, while snapshot hashes identify the actual development sources. No release lockfile installer, published compatibility matrix, or automatic six-package version selection exists. Changing a version field alone does not update installed files or running services.'),
h('Maintain Documentation with Code'),
p('Update the implementation contract when ownership or behavior changes. Update these procedures when commands or refresh steps change. Keep installation examples in the package README and the HTML handoff linked to the maintained corpus. Keep dated test results and user acceptance reports in objective artifacts rather than turning reference pages into status reports.') ]},
{path:base+'/40-recovery',title:'Validation and Recovery',blocks:[
p('Start with doctor for installed-file differences, discovery for workspace coverage, and a small real edit for end-to-end acceptance. These checks answer different questions.'),
h('Repeatable Acceptance'),
p('1. Open a new client session in the target project. Ask it to explain one existing documentation page without editing. Expect docs_discover and a tree, search, or read call against the correct project ID.'),
p('2. Ask for one source-supported documentation correction without naming the tools. Expect docs_begin before mutation, docs_read for the current document hash, and a typed edit with the returned task_id and expected_hash. docs_guidance is useful for a component-specific reference but is not required on every edit.'),
p('3. Expect docs_check on each changed page and docs_end when the task finishes. Read back the page and inspect it in the shared UI. A successful tool response alone does not establish that the prose is correct.'),
p('4. For a Canvas or Sequence edit, expect docs_component_read and an advertised typed component action using the document and sidecar revision hashes. For a multi-project request, verify each project separately and report partial success explicitly.'),
p('5. Repeat the implicit request in each supported coding client. Separately exercise a built-in agent through its existing staged review flow after shared guidance changes. Protocol tests, installer checks, and external edits do not prove model behavior in every client.'),
h('Find Tool Names'),c('bun packages/docs-mcp/src/cli.ts tools\nbun packages/docs-mcp/src/cli.ts doctor\nbun packages/docs-mcp/src/cli.ts discover --workspace ..'),
p('Use advertised schemas for exact arguments. Common edits include docs_write_text, docs_insert, and docs_apply_ops. Component action names are generated from the registered actions; do not infer a name or bypass an unsupported action with a filesystem write.'),
h('Connection and Discovery Failures'),table(['Symptom','Cause to check','Recovery'],[
['Tools absent','Client has not loaded its config or pi extension; configured checkout path moved.','Run doctor, preview reinstall, restart client or reload pi.'],
['No projects or wrong project','Wrong workspace, undeclared member, invalid docsRoot, or no normalized corpus.','Inspect discovery warnings; declare relative members; rediscover in the intended workspace.'],
['Unknown task or project','Task belongs to another workspace, service restarted, or project identity changed.','Rediscover; begin a new task; reread the target.'],
['Another checkout owns the service','A healthy daemon belongs to a different package root.','Finish work and stop that service before switching installations.'],
['Service will not start','Startup or dependency failure.','Inspect service.log in the configured state directory; correct the reported error before reconnecting.']]),
h('Editing Failures'),table(['Symptom','Meaning','Recovery'],[
['Revision conflict','Content changed after the read.','Read again, reconcile the intended change, and submit the fresh hash.'],
['Sidecar revision conflict','Embedded Canvas or Sequence state changed.','Reread both document and component; reconcile both revisions.'],
['Implementation changed','Imported source differs from the running service.','Finish or abandon the task, restart service and clients, and begin again.'],
['Required lint or invalid structure','The operation or final page violates a checked rule.','Inspect returned findings and repair through typed tools; do not rewrite doc.json.'],
['Undo unavailable or rejected','Patch is outside this process, belongs elsewhere, has a conflicting revision, or is page creation.','Use a new reviewed typed correction. Page creation has no exposed undo.']]),
h('Backups and Restore'),c('bun packages/docs-mcp/src/cli.ts restore /tmp/codecaine-docs-install.json\nbun packages/docs-mcp/src/cli.ts restore /tmp/codecaine-docs-install.json --write'),
p('Preview restore first. Restore verifies backup and installed-file hashes and refuses to overwrite post-install changes. Claude can update its configuration during normal use, so an exact restore may refuse. To remove only its MCP entry, use claude mcp remove codecaine-docs -s user and preserve the newer file. Skill copies and pi configuration require their own reviewed cleanup.'),
h('Local State and Evidence'),
p('Runtime state defaults to ~/.local/state/codecaine-docs or CODECAINE_DOCS_STATE_DIR. daemon.json contains the bearer credential and service address. daemon.lock and startup.lock coordinate startup; service.log records daemon output. Do not share daemon.json as a diagnostic artifact. No model API key is needed for this editing service.'),
p('Task contexts and guarded undo are process-local. docs_end releases guidance and does not revert applied edits. Stopping the service loses that in-memory state, while saved documents remain on disk. Cross-project edits are not atomic.'),
p('Save tool results, final hashes, lint findings, and a reviewed content diff when recording acceptance. Label a user-reported successful exercise separately from automated evidence. Keep those dated records in objectives/docs-mcp-integration/artifacts and the handoff, outside the maintained corpus.') ]}
];
let task:string|undefined;
try{
 await client.connect(new StdioClientTransport({command:process.execPath,args:[join(repo,'packages/docs-mcp/src/cli.ts'),'mcp','--workspace',core]}));
 const found=await call('docs_discover');const project=found.projects.find((p:any)=>p.name==='docs-system').id;
 const existing=JSON.parse(await readFile('/tmp/docs-maint-begin.json','utf8')).structuredContent;task=existing.task_id;
 await call('docs_guidance',{task_id:task});
 async function append(path:string,blocks:any[],prefix:string){const r=await call('docs_read',{project,path});const root=r.doc.root;const start=r.doc.blocks[root].children.length;
 if(Object.keys(r.doc.blocks).some(x=>x.startsWith(prefix)))throw Error('Already authored: '+path);
 await call('docs_apply_ops',{project,path,task_id:task,expected_hash:r.hash,ops:blocks.map((b,i)=>({type:'insertBlock',blockId:prefix+i,parentId:root,index:start+i,blockType:b.type,props:b.props,...(b.text?{text:b.text}:{})}))});}
 for(const spec of specs){await call('docs_create',{project,path:spec.path,title:spec.title,expected_absent:true,task_id:task});await append(spec.path,spec.blocks,'maintenance-');}
 await append(impl,[h('Maintained Procedures'),link('Docs MCP Maintenance',base,' contains the setup, skill-authoring, synchronization, and recovery procedures.'),h('Process and Task Ownership'),p('Codex and Claude use stdio MCP bridges; pi uses its extension bridge. They connect to one authenticated loopback daemon per state directory. The service resolves an explicit project to its canonical docs root and calls the existing store through typed tools. No model or kernel process is started by an external documentation task.'),p('The service owns workspace membership and in-memory task snapshots. Store operations own structural validation, revision checks, and root-scoped mutation coordination. Task IDs are bound to the workspace; they pin authoring knowledge without creating a transaction. Direct valid edits persist immediately. The shared workbench proxies to this same daemon. Standalone workbenches and kernel processes retain independent process-local state.'),h('Maintained and Derived Files'),tree([
['packages/docs-mcp/src/cli.ts','Command dispatch, workspace defaults, setup and diagnostics'],['packages/docs-mcp/src/mcp.ts','MCP tools, instructions, guidance resource, client workspace roots'],['packages/docs-mcp/src/pi-extension.ts','pi tool registration and bridge'],['packages/docs-mcp/src/service.ts','Project membership, tasks, guidance and mutation gate'],['packages/docs-mcp/src/tools.ts','Typed Docs operations and generated component actions'],['packages/docs-mcp/src/discovery.ts','Workspace member and normalized-corpus discovery'],['packages/docs-mcp/src/daemon.ts','Authenticated local HTTP service'],['packages/docs-mcp/src/lifecycle.ts','State directory, startup locks and checkout ownership'],['packages/docs-mcp/src/install.ts','Client configuration, skill generation, backups, doctor and restore'],['packages/docs-mcp/src/guidance.ts','Canonical guidance loading and generated skill references'],['packages/docs-mcp/src/snapshot.ts','Development source and tool-contract fingerprinting'],['packages/docs-mcp/skills/codecaine-docs/','Maintained SKILL.md plus generated references and snapshot'],['packages/docs-model/src/authoring-guidance.ts','Shared renderer for internal and external authors'],['packages/docs-model/src/components/','Registered schemas, actions, rendering and authoring metadata'],['packages/docs-server/src/store.ts','Canonical document mutation authority'],['packages/docs-workbench/src/shared-api.ts','Shared UI proxy'],['packages/docs-kernel/catalog/docs-lab-editor/context/index.ts','Internal Docs Lab authoring context consumer']]),h('Ecosystem Coverage'),p('The implemented adapter edits Docs corpora, including documentation for other packages when those corpora are discoverable. Embedded Canvas and Sequence operations use the Docs component adapters. This does not provide standalone Canvas, Sequence, PromptKit, Annotations, or Agent Kernel product services. Recording sibling repositories in a development snapshot does not establish adapter support.'),p('Canonical corpus standards, style documents, component references, manifests, and the source skill feed generated knowledge. Installed skill references are copies. Internal context loaders share the renderer while retaining their own prompts and staged editing lifecycle. Runtime source fingerprints guard against using changed implementation files in an existing service. Published release compatibility and automatic package-version resolution remain unimplemented.')],'maintenance-');
 await append('20-implementation/10-packages',[link('Docs MCP',impl,' connects external coding clients to the Docs store and shares maintained authoring guidance.')],'mcp-index-');
 for(const path of [...specs.map(s=>s.path),impl,'20-implementation/10-packages']){await call('docs_check',{project,path});const r=await call('docs_read',{project,path});evidence.push({path,hash:r.hash,markdown:r.markdown});for(const b of Object.values(r.doc.blocks) as any[]){for(const span of b.text??[]){const ref=span.attributes?.reference;if(ref?.kind==='doc')await call('docs_read',{project,path:ref.path});if(ref?.kind==='source')await access(join(repo,ref.path));}}}
 await call('docs_end',{task_id:task});task=undefined;
}finally{if(task)await call('docs_end',{task_id:task}).catch(()=>{});await client.close();await writeFile(join(import.meta.dir,'maintenance-docs-results.json'),JSON.stringify(evidence,null,2)+'\n');}
console.log('Maintenance docs saved; see maintenance-docs-results.json for checks and readback.');
