/**
 * Technical nouns and verbs: project vocabulary on top of the STE approved words. Each term has
 * one meaning in this corpus. The deny list never holds one of these terms.
 *
 * Multi-word nouns matter most: the noun-cluster rule counts a registered multi-word noun as one
 * noun, so "the file tree block renderer" has 3 nouns, not 4. Terms are lowercase and singular,
 * and a rule matches plurals itself.
 */
import type { Term } from "./types";

/** The Vocabulary page's 39 technical nouns, in page order. */
const vocabularyNouns: readonly Term[] = [
  { term: "page", meaning: "One unit that a reader opens, stored as one bundle." },
  { term: "bundle", meaning: "The folder of one page, with its doc.json, sidecars, and assets." },
  { term: "doc.json", meaning: "The file that stores one page as a block tree." },
  { term: "document", meaning: "The data-model object for one page." },
  { term: "corpus", meaning: "All pages under one docs root." },
  { term: "docs root", meaning: "The folder that holds one corpus." },
  { term: "project", meaning: "A repo with a docs corpus, which tools address by project ID." },
  { term: "layer", meaning: "One of the four numbered root folders, from 00-foundation to 30-implementation." },
  { term: "section", meaning: "A folder below a layer that is also a page and introduces its children." },
  { term: "parent page", meaning: "The page of a layer or section folder, which introduces each child in one line." },
  { term: "block", meaning: "One unit of content, with a stable ID, a type, props, and optional text." },
  { term: "block type", meaning: "The kind of a block, such as paragraph or file-tree." },
  { term: "block id", meaning: "A stable ID that is unique in its page." },
  { term: "props", meaning: "The typed state fields of a block." },
  { term: "state schema", meaning: "The closed schema for the props of a block type." },
  { term: "component", meaning: "The code for one or more block types." },
  { term: "action", meaning: "A named, checked change to one block, such as file-tree.addEntry." },
  { term: "reference", meaning: "An inline link to a page or a source file." },
  { term: "backlinks index", meaning: "The SQLite index of inbound references." },
  { term: "doc renderer", meaning: "The React code that shows a block type to a person." },
  { term: "agent renderer", meaning: "The function that writes block state as markdown for agents." },
  { term: "op", meaning: "One of the 7 document changes, such as insertBlock." },
  { term: "patch", meaning: "One applied batch of ops, which is the unit of undo." },
  { term: "proposal", meaning: "A staged batch of ops for one page that waits for a reviewer." },
  { term: "change set", meaning: "A group of proposals that a reviewer accepts, rejects, or undoes as one unit." },
  { term: "content hash", meaning: "The SHA-256 hash of the bytes of a file, which makes a write fail if the file changed." },
  { term: "session", meaning: "One run of an agent or one editor tab, whose writes share one session_id." },
  { term: "sidecar", meaning: "A JSON file beside doc.json that holds state other than content." },
  { term: "asset", meaning: "A file in the assets/ folder of a bundle, such as an image." },
  { term: "annotation", meaning: "A note or an agent request on a block, a text range, or a canvas object." },
  { term: "lint rule", meaning: "A registered writing or structure rule with an ID and a severity." },
  { term: "finding", meaning: "One match of a lint rule on a page." },
  { term: "baseline", meaning: "The page as it was before the first write of a task." },
  { term: "judgment rule", meaning: "A style rule that a model answers with a confidence score." },
  { term: "style gate", meaning: "The gated findings that a task added, which make docs_check fail." },
  { term: "task", meaning: "One authoring activity, from docs_begin to docs_end." },
  { term: "viewer", meaning: "The React package that shows and edits pages." },
  { term: "workbench", meaning: "The local app that docs serve starts." },
  { term: "board", meaning: "One canvas file, which a canvas block points to." },
];

/**
 * Multi-word block type names from DOC_BLOCK_TYPES, written with spaces, plus "code block" for the
 * code type. The list keeps "flow strip", which DOC_BLOCK_TYPES no longer holds.
 */
const blockTypeNouns: readonly Term[] = [
  { term: "list item", meaning: "The block type for one bullet or numbered item." },
  { term: "code block", meaning: "The block type for source code, with optional side notes." },
  { term: "structured table", meaning: "The block type for a typed table of columns and rows." },
  { term: "file tree", meaning: "The block type for a tree of file paths with notes and change marks." },
  { term: "file explorer", meaning: "The block type for editor-sidebar rows of files with change badges." },
  { term: "state shape", meaning: "The block type for the field tree of a state, with an example." },
  { term: "interaction surface", meaning: "The block type for the operations that change or query a system." },
  { term: "image grid", meaning: "The block type for ordered images in responsive columns." },
  { term: "process outline", meaning: "The block type for an ordered tree of process steps." },
  { term: "call stack", meaning: "The block type for one code path, frame by frame." },
  { term: "component tree", meaning: "The block type for a render tree of components, hooks, and branches." },
  { term: "flow strip", meaning: "A removed block type that showed a row of numbered step cards joined by arrows." },
];

/** Other multi-word nouns of the docs system, mined from the corpus and its glossary candidates. */
const domainNouns: readonly Term[] = [
  // Data model and writes
  { term: "docs system", meaning: "The product in the docs-system repo, with its docs model, tools, and apps." },
  { term: "component family", meaning: "A group of block types that one component defines, such as rich text." },
  { term: "block contract", meaning: "The six parts each block type defines, from its state schema to its agent adapter." },
  { term: "agent adapter", meaning: "The part of a block type that lets an agent edit it to handle an annotation." },
  { term: "context loader", meaning: "The part of an agent adapter that collects the state an agent needs." },
  { term: "delta span", meaning: "One run of rich text, made of an insert string and optional marks." },
  { term: "delta text", meaning: "The text of a block, stored as delta spans." },
  { term: "rich text", meaning: "Text with inline marks, such as bold, code, and links." },
  { term: "code span", meaning: "Inline text in code font, which no rule edits." },
  { term: "typed action", meaning: "An action of a block type whose params a schema checks." },
  { term: "component action", meaning: "The op that runs one typed action on a block." },
  { term: "forwarded action", meaning: "An action that canvas or sequence applies to its own sidecar." },
  { term: "props patch", meaning: "The partial props that an action returns for an op to apply." },
  { term: "operation signature", meaning: "One operation of an interaction surface, with its params and its result." },
  { term: "field ledger", meaning: "The rows of fields in a state shape or an operation card." },
  { term: "step tree", meaning: "The nested steps that a process outline holds." },
  { term: "header row", meaning: "The first row of a structured table, which holds the column names." },
  { term: "canvas object", meaning: "A shape, sticky, or icon on a board." },
  { term: "sequence diagram", meaning: "A diagram of the messages between participants, which a sequence block shows." },
  { term: "undo ledger", meaning: "The in-memory store of inverse batches, keyed by patch ID." },
  { term: "inverse batch", meaning: "The ops that revert one applied patch." },
  { term: "patch id", meaning: "The ID of one applied patch, which undo takes." },
  { term: "task id", meaning: "The ID of one authoring task." },
  { term: "project id", meaning: "The ID that tools use to address a project." },
  { term: "draft lock", meaning: "An expiring write claim that one session holds." },
  { term: "write authority", meaning: "The server part that checks and writes each page in one critical section." },
  { term: "hash precondition", meaning: "The content hash that a write expects, so a stale write fails." },
  { term: "change event", meaning: "The message the server sends after a write commits." },
  { term: "validation issue", meaning: "A typed problem that a validator returns with a path." },
  { term: "agent request", meaning: "An annotation that asks an agent to change a page." },
  { term: "annotation thread", meaning: "An annotation with its replies." },
  { term: "agent run", meaning: "The receipt on a handled annotation, with its session ID, patch ID, and summary." },
  // Surfaces and apps
  { term: "translation layer", meaning: "The one stored page state that people and agents both read." },
  { term: "human surface", meaning: "The rendered page where a person reads and edits blocks." },
  { term: "agent surface", meaning: "The markdown and typed tools that agents use to read and edit pages." },
  { term: "reading surface", meaning: "The read view of a page in the viewer." },
  { term: "markdown projection", meaning: "The markdown form of a page that the agent renderers write." },
  { term: "node view", meaning: "The editor view that draws one block in place." },
  { term: "edit mode", meaning: "The workbench mode in which a person edits a page." },
  { term: "annotate mode", meaning: "The workbench mode in which a person adds annotations." },
  { term: "slash menu", meaning: "The editor menu that a slash opens, to insert a block." },
  { term: "reference peek", meaning: "The read-only panel that opens on a page reference." },
  { term: "style rail", meaning: "The workbench panel that edits the styles of the active theme." },
  { term: "global theme", meaning: "The one shared theme that every project can render." },
  { term: "theme folder", meaning: "The folder that holds the files of one theme." },
  { term: "theme file", meaning: "The style file of one block type in a theme folder." },
  { term: "theme knob", meaning: "A style setting that a component exposes and each theme sets." },
  { term: "code theme", meaning: "The syntax colors that every code surface uses." },
  { term: "central docs service", meaning: "The signed local service that routes projects and runs the docs MCP." },
  { term: "docs mcp", meaning: "The MCP server that gives agents the docs tools." },
  // Doc standards
  { term: "concept page", meaning: "A level-3 page that covers one idea." },
  { term: "area page", meaning: "An implementation-layer page that mirrors one source folder and holds its decisions." },
  { term: "depth ladder", meaning: "The six levels, L1 to L6, from the parent page of a layer down to the code." },
  { term: "extension tier", meaning: "A numbered root folder from 40 to 98 that holds guides." },
  { term: "lint engine", meaning: "The docs-model code that runs lint rules on a page." },
  { term: "style guide", meaning: "The pages that define how to write and structure a page." },
  { term: "style digest", meaning: "The short list of top style rules that docs_begin returns." },
  { term: "house style", meaning: "The writing rules of this corpus on top of STE." },
  // Style enforcement
  { term: "ste profile", meaning: "Our software version of the ASD-STE100 writing standard." },
  { term: "deny list", meaning: "The words and phrases that the profile replaces or flags." },
  { term: "replacement table", meaning: "A table of rejected words and the words to write instead." },
  { term: "naming canon", meaning: "The one name to use for each concept." },
  { term: "technical noun", meaning: "A project noun that extends the STE approved words." },
  { term: "technical verb", meaning: "A software verb that extends the STE approved words." },
  { term: "noun cluster", meaning: "A run of nouns, such as \"import budget check script\"." },
  { term: "structure rule", meaning: "A style rule about sentence and block shape, which can gate a page." },
  { term: "vocabulary rule", meaning: "A style rule about word choice, which only suggests." },
  { term: "fix op", meaning: "An op on a lint finding that fixes it." },
  { term: "rewrite model", meaning: "The cheap model that rewrites blocks with structure findings." },
  { term: "fact ledger", meaning: "The facts that a rewrite must keep, such as code spans, numbers, and names." },
  { term: "meaning word", meaning: "A limit or logic word, such as \"not\", whose count a rewrite must keep." },
  { term: "shrink limit", meaning: "The most of its words that a rewrite can remove." },
  { term: "slop word", meaning: "A word that marks model-written filler, such as \"robust\"." },
];

export const technicalNouns: readonly Term[] = [...vocabularyNouns, ...blockTypeNouns, ...domainNouns];

/** The Vocabulary page's "Software Verbs STE Rejects" and "Docs System Verbs". */
export const technicalVerbs: readonly Term[] = [
  // Software verbs that STE rejects
  { term: "run", meaning: "Start a program, a script, or a check." },
  { term: "create", meaning: "Make a new file, page, block, or object." },
  { term: "call", meaning: "Start a function or a tool with arguments." },
  { term: "return", meaning: "Give a value back to the caller." },
  { term: "build", meaning: "Compile or package code." },
  { term: "render", meaning: "Make the visible form or the markdown form of a page or block." },
  { term: "link", meaning: "Point one page or object at another." },
  { term: "search", meaning: "Find text across pages or files." },
  { term: "test", meaning: "Run code that checks other code." },
  { term: "handle", meaning: "Respond to an event, an error, or a request." },
  { term: "define", meaning: "State the name and shape of a type, a term, or a rule." },
  { term: "generate", meaning: "Make code or text with a program or a model." },
  // Docs system verbs
  { term: "read", meaning: "Load a page with its markdown, block IDs, hash, and findings." },
  { term: "apply", meaning: "Run a batch of ops on a page as one atomic write." },
  { term: "insert", meaning: "Add a new block under a parent at an index." },
  { term: "update", meaning: "Change the props or text of an item and keep its ID." },
  { term: "delete", meaning: "Remove a block, a page, or an asset." },
  { term: "move", meaning: "Take an item from one place and put it at another." },
  { term: "split", meaning: "Divide one text block, or one page, into two." },
  { term: "merge", meaning: "Join sibling blocks, or two pages, into one." },
  { term: "stage", meaning: "Record ops as a proposal for review instead of applying them." },
  { term: "accept", meaning: "Apply a staged proposal or change set." },
  { term: "reject", meaning: "Drop a staged proposal or change set with no change to content." },
  { term: "undo", meaning: "Apply the inverse batch of one patch." },
  { term: "validate", meaning: "Compare data with its schema and return typed problems." },
  { term: "lint", meaning: "Run lint rules on a page and report findings." },
  { term: "check", meaning: "Run validation and lint rules on a page, as docs_check does." },
  { term: "fix", meaning: "Apply safe, undoable repairs for lint findings." },
  { term: "annotate", meaning: "Put an annotation on a block, a text range, or a canvas object." },
  { term: "resolve", meaning: "Close an annotation, with an optional note." },
  { term: "reply", meaning: "Add a message to an annotation thread." },
];
