/** Serve the project directory with local filtering and progress for device registration. */
import type { DocsProject } from '../discovery';

const escape = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
/**
 * The page links the design-system package at /@codecaine-ai/design-system/<package path>, which the
 * docs service serves from the package docs-mcp resolves (design-system-assets.ts): fonts.css, then the
 * dark-first tokens. Colors, type, radii and borders come from --ds-* tokens, and so does every
 * spacing step a space token equals. The body keeps the browser's root size (the size the rem tokens assume).
 * Kept layout with no equal space token: the 850px column, its 72px top margin (layout.topbar.height
 * is 72px but names the shell topbar), the input's 18px and the button's 9px padding, the rows' 7px gap
 * and 22px padding, and the status lines' 1.6 line height.
 */
export function directoryHtml(projects: DocsProject[], version: string) {
  const rows = [...projects].sort((a, b) => a.name.localeCompare(b.name) || a.root.localeCompare(b.root)).map(p => `<a class="project" href="/projects/${encodeURIComponent(p.id)}/docs/"><strong>${escape(p.name)}</strong><span>${escape(p.root)}</span><b aria-hidden="true">↗</b></a>`).join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Codecaine Docs</title>
<link rel="stylesheet" href="/@codecaine-ai/design-system/css/fonts.css"><link rel="stylesheet" href="/@codecaine-ai/design-system/dist/css/tokens-dark-first.css">
<style>
*{box-sizing:border-box}body{margin:0;background:var(--ds-color-surface-page);color:var(--ds-color-text-body);font-family:var(--ds-font-family-sans)}main{max-width:850px;margin:72px auto;padding:0 var(--ds-space-7)}h1{color:var(--ds-color-text-ink);font-size:var(--ds-font-size-title);font-weight:var(--ds-font-weight-semibold);letter-spacing:var(--ds-letter-spacing-title);margin:var(--ds-space-2) 0 var(--ds-space-7)}p{color:var(--ds-color-text-secondary);line-height:1.6}small,.muted{color:var(--ds-color-text-muted)}.toolbar{display:flex;gap:var(--ds-space-3);align-items:center;margin:var(--ds-space-4) 0 var(--ds-space-2)}input{width:100%;font:inherit;padding:var(--ds-space-4) 18px;background:var(--ds-color-surface-panel);color:inherit;border:var(--ds-border-width-hairline) solid var(--ds-color-border-default);border-radius:var(--ds-radius-base)}input:focus,button:focus-visible,a:focus-visible{outline:var(--ds-border-width-focus) solid var(--ds-color-focus-ring);outline-offset:var(--ds-focus-ring-offset)}button{font:inherit;font-size:var(--ds-font-size-ui-sm);border:var(--ds-border-width-hairline) solid var(--ds-color-border-default);border-radius:var(--ds-radius-base);background:transparent;color:var(--ds-color-text-body);padding:9px var(--ds-space-3);cursor:pointer;white-space:nowrap}button:disabled{opacity:.6;cursor:wait}#count{flex:1;font-size:var(--ds-font-size-ui-sm)}#scan-status,#service-status,details{font-size:var(--ds-font-size-ui-sm)}#scan-status{margin:var(--ds-space-2) 0}details{color:var(--ds-color-text-secondary);margin:var(--ds-space-3) 0}details ul{padding-left:var(--ds-space-5);overflow-wrap:anywhere}summary{cursor:pointer}.project{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;padding:22px 0;border-bottom:var(--ds-border-width-hairline) solid var(--ds-color-border-subtle);color:inherit;text-decoration:none}.project:hover strong{color:var(--ds-color-link)}.project strong{color:var(--ds-color-text-ink);font-size:var(--ds-font-size-reading);font-weight:var(--ds-font-weight-semibold)}.project span{grid-column:1;color:var(--ds-color-text-muted);font-size:var(--ds-font-size-ui-xs);overflow-wrap:anywhere}.project b{grid-column:2;grid-row:1/3;align-self:center;font-size:var(--ds-font-size-reading);font-weight:var(--ds-font-weight-regular);color:var(--ds-color-link)}footer{margin:var(--ds-space-8) 0;font-size:var(--ds-font-size-ui-xs)}[hidden]{display:none!important}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}@media(max-width:520px){main{margin:var(--ds-space-8) auto;padding:0 var(--ds-space-5)}.toolbar{flex-wrap:wrap}}
</style></head><body><main><small>CODECAINE</small><h1>Documentation</h1>
<label for="search" class="sr-only">Search projects by name or folder</label><input id="search" type="search" placeholder="Search docs…" autocomplete="off" spellcheck="false">
<div class="toolbar"><span id="count" class="muted" role="status"></span><button id="scan" type="button">Register docs on this device</button></div>
<p id="scan-status" role="status"></p><p id="service-status" role="status" hidden></p>
<details id="scan-details" hidden><summary id="scan-summary"></summary><ul id="scan-warnings"></ul></details>
<div id="projects">${rows}</div><p id="empty" hidden>No projects match your search.</p>
<footer class="muted">Native Codecaine Docs in your user folders, registered workspaces and mounted drives. System folders, dependencies and backups are skipped.<br>Docs ${escape(version)}</footer>
</main><script>
const search=document.getElementById('search'),list=document.getElementById('projects'),count=document.getElementById('count'),empty=document.getElementById('empty'),button=document.getElementById('scan'),scanStatus=document.getElementById('scan-status'),serviceStatus=document.getElementById('service-status');
let signature='',refreshing=false,starting=false,autoStarted=false;
function filter(){const query=search.value.trim().toLocaleLowerCase();let visible=0;for(const row of list.children){const matches=row.textContent.toLocaleLowerCase().includes(query);row.hidden=!matches;if(matches)visible++}count.textContent=query?visible+' of '+list.children.length+' projects':list.children.length+' projects';empty.hidden=visible>0;empty.textContent=query?'No projects match your search.':'No registered docs yet. Device discovery will add them here.'}
function renderProjects(projects){const next=JSON.stringify(projects);if(next===signature)return;signature=next;const fragment=document.createDocumentFragment();projects.sort((a,b)=>a.name.localeCompare(b.name)||a.root.localeCompare(b.root));for(const p of projects){const row=document.createElement('a');row.className='project';row.href='/projects/'+encodeURIComponent(p.id)+'/docs/';const title=document.createElement('strong');title.textContent=p.name;const path=document.createElement('span');path.textContent=p.root;const arrow=document.createElement('b');arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');row.append(title,path,arrow);fragment.append(row)}list.replaceChildren(fragment);filter()}
function renderScan(scan){const busy=scan.phase==='scanning';button.disabled=busy||starting;button.textContent=busy?'Scanning device…':'Register docs on this device';scanStatus.textContent=busy?'Scanning · '+scan.folders+' folders checked · '+scan.added+' projects added':scan.phase==='complete'?'Device scan complete · '+scan.added+' projects added':scan.phase==='failed'?'Device scan failed. Use the button to retry.':scan.phase==='interrupted'?'Previous scan interrupted. Use the button to resume.':'Docs are discovered automatically on your first visit.';const details=document.getElementById('scan-details');details.hidden=!scan.skipped;document.getElementById('scan-summary').textContent=scan.skipped+' discovery notices';const warnings=document.getElementById('scan-warnings');warnings.replaceChildren(...scan.warnings.map(w=>{const li=document.createElement('li');li.textContent=w;return li}));if(scan.skipped>scan.warnings.length){const li=document.createElement('li');li.textContent='Showing the first '+scan.warnings.length+' notices.';warnings.append(li)}}
async function startScan(){if(starting)return;starting=true;button.disabled=true;try{const response=await fetch('/api/discovery',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});if(!response.ok)throw new Error('Discovery could not start. Retry when the service is ready.');autoStarted=true;renderScan(await response.json())}catch(e){serviceStatus.hidden=false;serviceStatus.textContent=e.message}finally{starting=false;button.disabled=false;void refresh()}}
async function refresh(){if(refreshing)return;refreshing=true;try{const responses=await Promise.all(['/api/projects','/api/discovery','/api/status'].map(url=>fetch(url,{cache:'no-store'})));if(responses.some(r=>!r.ok))throw new Error('Docs is reconnecting…');const [data,scan,status]=await Promise.all(responses.map(r=>r.json()));renderProjects(data.projects);renderScan(scan);serviceStatus.hidden=!status.error;serviceStatus.textContent=status.error?'Service update failed. The previous build is still running.':'';if(!autoStarted&&scan.phase==='idle'&&status.ready)void startScan()}catch(e){serviceStatus.hidden=false;serviceStatus.textContent=e.message}finally{refreshing=false}}
search.addEventListener('input',filter);button.addEventListener('click',startScan);filter();void refresh();setInterval(refresh,2000);
</script></body></html>`;
}
