/** Serve the project directory with local filtering and progress for device registration. */
import type { DocsProject } from '../discovery';

const escape = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export function directoryHtml(projects: DocsProject[], version: string) {
  const rows = [...projects].sort((a, b) => a.name.localeCompare(b.name) || a.root.localeCompare(b.root)).map(p => `<a class="project" href="/projects/${encodeURIComponent(p.id)}/docs/"><strong>${escape(p.name)}</strong><span>${escape(p.root)}</span><b aria-hidden="true">↗</b></a>`).join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Codecaine Docs</title>
<style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#101315;color:#edf0ee;font:16px system-ui}main{max-width:850px;margin:72px auto;padding:0 28px}h1{font-size:36px;font-weight:550;letter-spacing:-1px;margin:8px 0 28px}p{color:#aeb6b2;line-height:1.6}small,.muted{color:#919d96}.toolbar{display:flex;gap:12px;align-items:center;margin:16px 0 8px}input{width:100%;font:inherit;padding:16px 18px;background:#1a2022;color:inherit;border:1px solid #3a4546;border-radius:10px}input:focus,button:focus-visible,a:focus-visible{outline:2px solid #a8d3bd;outline-offset:3px}button{font:inherit;font-size:13px;border:1px solid #3a4546;border-radius:7px;background:transparent;color:#c9d9d2;padding:9px 12px;cursor:pointer;white-space:nowrap}button:disabled{opacity:.6;cursor:wait}#count{flex:1;font-size:13px}#scan-status,#service-status,details{font-size:13px}#scan-status{margin:8px 0}details{color:#aeb6b2;margin:12px 0}details ul{padding-left:20px;overflow-wrap:anywhere}summary{cursor:pointer}.project{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;padding:22px 0;border-bottom:1px solid #303734;color:inherit;text-decoration:none}.project:hover strong{color:#a8d3bd}.project strong{font-size:20px;font-weight:550}.project span{grid-column:1;color:#919d96;font-size:12px;overflow-wrap:anywhere}.project b{grid-column:2;grid-row:1/3;align-self:center;font-size:22px;font-weight:400;color:#a8d3bd}footer{margin:32px 0;font-size:12px}[hidden]{display:none!important}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}@media(max-width:520px){main{margin:32px auto;padding:0 20px}h1{font-size:30px}.toolbar{flex-wrap:wrap}}
</style></head><body><main><small>CODECAINE</small><h1>Documentation</h1>
<label for="search" class="sr-only">Search projects by name or folder</label><input id="search" type="search" placeholder="Search docs…" autocomplete="off" spellcheck="false">
<div class="toolbar"><span id="count" class="muted" role="status"></span><button id="scan" type="button">Register docs on this device</button></div>
<p id="scan-status" role="status"></p><p id="service-status" role="status" hidden></p>
<details id="scan-details" hidden><summary id="scan-summary"></summary><ul id="scan-warnings"></ul></details>
<div id="projects">${rows}</div><p id="empty" hidden>No projects match your search.</p>
<footer class="muted">Native Codecaine Docs in your user folders, registered workspaces and mounted drives. System folders, dependencies and backups are skipped.<br>Docs ${escape(version)}</footer>
</main><script>
const search=document.getElementById('search'),list=document.getElementById('projects'),count=document.getElementById('count'),empty=document.getElementById('empty'),button=document.getElementById('scan'),scanStatus=document.getElementById('scan-status'),serviceStatus=document.getElementById('service-status');
let signature='',refreshing=false,starting=false,autoStarted=false;
function filter(){const query=search.value.trim().toLocaleLowerCase();let visible=0;for(const row of list.children){const matches=row.textContent.toLocaleLowerCase().includes(query);row.hidden=!matches;if(matches)visible++}count.textContent=query?visible+' of '+list.children.length+' projects':list.children.length+' projects';empty.hidden=visible>0;empty.textContent=query?'No projects match your search.':'No registered docs yet. Device discovery will add them here.'}
function renderProjects(projects){const next=JSON.stringify(projects);if(next===signature)return;signature=next;const fragment=document.createDocumentFragment();projects.sort((a,b)=>a.name.localeCompare(b.name)||a.root.localeCompare(b.root));for(const p of projects){const row=document.createElement('a');row.className='project';row.href='/projects/'+encodeURIComponent(p.id)+'/docs/';const title=document.createElement('strong');title.textContent=p.name;const path=document.createElement('span');path.textContent=p.root;const arrow=document.createElement('b');arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');row.append(title,path,arrow);fragment.append(row)}list.replaceChildren(fragment);filter()}
function renderScan(scan){const busy=scan.phase==='scanning';button.disabled=busy||starting;button.textContent=busy?'Scanning device…':'Register docs on this device';scanStatus.textContent=busy?'Scanning · '+scan.folders+' folders checked · '+scan.added+' projects added':scan.phase==='complete'?'Device scan complete · '+scan.added+' projects added':scan.phase==='failed'?'Device scan failed. Use the button to retry.':scan.phase==='interrupted'?'Previous scan interrupted. Use the button to resume.':'Docs are discovered automatically on your first visit.';const details=document.getElementById('scan-details');details.hidden=!scan.skipped;document.getElementById('scan-summary').textContent=scan.skipped+' discovery notices';const warnings=document.getElementById('scan-warnings');warnings.replaceChildren(...scan.warnings.map(w=>{const li=document.createElement('li');li.textContent=w;return li}));if(scan.skipped>scan.warnings.length){const li=document.createElement('li');li.textContent='Showing the first '+scan.warnings.length+' notices.';warnings.append(li)}}
async function startScan(){if(starting)return;starting=true;button.disabled=true;try{const response=await fetch('/api/discovery',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});if(!response.ok)throw new Error('Discovery could not start. Retry when the service is ready.');autoStarted=true;renderScan(await response.json())}catch(e){serviceStatus.hidden=false;serviceStatus.textContent=e.message}finally{starting=false;button.disabled=false;void refresh()}}
async function refresh(){if(refreshing)return;refreshing=true;try{const responses=await Promise.all(['/api/projects','/api/discovery','/api/status'].map(url=>fetch(url,{cache:'no-store'})));if(responses.some(r=>!r.ok))throw new Error('Docs is reconnecting…');const [data,scan,status]=await Promise.all(responses.map(r=>r.json()));renderProjects(data.projects);renderScan(scan);serviceStatus.hidden=!status.error;serviceStatus.textContent=status.error?'Service update failed. The previous build is still running.':'';if(!autoStarted&&scan.phase==='idle'&&status.ready)void startScan()}catch(e){serviceStatus.hidden=false;serviceStatus.textContent=e.message}finally{refreshing=false}}
search.addEventListener('input',filter);button.addEventListener('click',startScan);filter();void refresh();setInterval(refresh,2000);
</script></body></html>`;
}
